docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY_PASSWORD
  script:
    - docker build --pull -t dominikosseqq/stats-app .
    - docker push dominikosseqq/stats-app
