docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build --pull -t dominikosseqq/stats-app ./myApp
    - docker push dominikosseqq/stats-app
    - docker build -pull -t dominikosseqq/stats-app-web ./myAppWeb/myAppWeb
    - docker push dominikosseqq/stats-app-web
