version: '3'
services:
    statsapp:
        build: 
            context: ./myApp
            dockerfile: Dockerfile
        container_name: Django_Backend
        volumes: 
            - ./myApp:/myApp
        ports: 
            - 8080:8080
        command: sh -c "/wait && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
        environment: 
            WAIT_HOSTS: postgres:5432
        depends_on: 
            - postgres
    postgres:
        image: postgres:9.6
        container_name: Postgres_DB
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: myApp
            PG_PASSWORD: admin
        ports: 
            - 5432:5432
        restart: always
    statsappweb:
        build: 
            context: ./myAppWeb/myAppWeb
            dockerfile: Dockerfile
        container_name: CRA_TS_Frontend
        stdin_open: true
        ports: 
            - 3000:3000
        command: yarn start
        restart: unless-stopped
        depends_on: 
            - statsapp
