# Generated by Django 3.0 on 2020-05-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=300)),
                ('author', models.CharField(default='author', max_length=50)),
                ('content', models.CharField(default='content', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='author', max_length=50)),
                ('words', models.CharField(default='words', max_length=10000)),
            ],
        ),
    ]
